// UI 개발용 임시 데이터. 서버 계약/Domain 모델이 아니며 연동 시 이 디렉토리를 통째로 삭제한다.

import type { DemoDispute } from './demoTypes'

export const DEMO_DISPUTES: DemoDispute[] = [
  {
    disputeId: 'D-61',
    proposalId: 'P-1029',
    offerId: 'O-399',
    missionId: 'M-189',
    requesterName: '강태오',
    requesterRole: '행님',
    targetName: '도경수',
    targetRole: '꼬붕',
    reasonQuestionText: '약속한 시간에 미션이 시작되지 않았어요.',
    detailReason: '시작 시간이 지나도록 연락이 닿지 않습니다.',
    status: '미처리',
    requestedAt: '2026-08-20 09:14',
  },
  {
    disputeId: 'D-59',
    proposalId: 'P-1028',
    offerId: 'O-397',
    missionId: 'M-187',
    requesterName: '진태현',
    requesterRole: '꼬붕',
    targetName: '조은비',
    targetRole: '행님',
    reasonQuestionText: '요청에 없던 작업을 요구받았어요.',
    detailReason: '미션 범위를 벗어난 추가 작업을 요구받았습니다.',
    status: '미처리',
    requestedAt: '2026-08-19 21:05',
  },
  {
    disputeId: 'D-58',
    proposalId: 'P-1020',
    offerId: 'O-392',
    missionId: 'M-182',
    requesterName: '한지우',
    requesterRole: '행님',
    targetName: '백지훈',
    targetRole: '꼬붕',
    reasonQuestionText: '미션 결과물이 요청 내용과 달라요.',
    detailReason: '요청한 물품 대신 다른 물품을 전달받았습니다.',
    status: '처리 완료',
    requestedAt: '2026-08-17 09:32',
  },
  {
    disputeId: 'D-55',
    proposalId: 'P-1008',
    offerId: 'O-380',
    missionId: 'M-175',
    requesterName: '천유빈',
    requesterRole: '꼬붕',
    targetName: '백승우',
    targetRole: '행님',
    reasonQuestionText: '미션 완료 확인이 지연되고 있어요.',
    detailReason: '완료를 알린 뒤 사흘이 지나도록 확인이 없습니다.',
    status: '처리 완료',
    requestedAt: '2026-08-13 08:20',
  },
]
