// UI 개발용 임시 데이터. 서버 계약/Domain 모델이 아니며 연동 시 이 디렉토리를 통째로 삭제한다.

import type { DemoMission } from './demoTypes'

export const DEMO_MISSIONS: DemoMission[] = [
  {
    missionId: 'M-193',
    proposalId: 'P-1031',
    offerId: 'O-405',
    hyungnimName: '최민재',
    kkobungName: '임도윤',
    status: '진행중',
    openChatUrl: 'https://open.kakao.com/o/gM193abc',
    createdAt: '2026-08-20 15:36',
  },
  {
    missionId: 'M-191',
    proposalId: 'P-1030',
    offerId: 'O-402',
    hyungnimName: '정유진',
    kkobungName: '안소미',
    status: '진행중',
    openChatUrl: 'https://open.kakao.com/o/gM191vwx',
    createdAt: '2026-08-20 11:24',
  },
  {
    missionId: 'M-189',
    proposalId: 'P-1029',
    offerId: 'O-399',
    hyungnimName: '강태오',
    kkobungName: '도경수',
    status: '분쟁중',
    openChatUrl: 'https://open.kakao.com/o/gM189def',
    createdAt: '2026-08-19 19:21',
  },
  {
    missionId: 'M-187',
    proposalId: 'P-1028',
    offerId: 'O-397',
    hyungnimName: '조은비',
    kkobungName: '진태현',
    status: '분쟁중',
    openChatUrl: 'https://open.kakao.com/o/gM187ghi',
    createdAt: '2026-08-19 14:48',
  },
  {
    missionId: 'M-186',
    proposalId: 'P-1027',
    offerId: 'O-396',
    hyungnimName: '윤성호',
    kkobungName: '우다인',
    status: '완료',
    openChatUrl: 'https://open.kakao.com/o/gM186jkl',
    createdAt: '2026-08-18 20:51',
  },
  {
    missionId: 'M-183',
    proposalId: 'P-1023',
    offerId: 'O-393',
    hyungnimName: '임채원',
    kkobungName: '조하람',
    status: '진행중',
    openChatUrl: 'https://open.kakao.com/o/gM183mno',
    createdAt: '2026-08-17 10:45',
  },
  {
    missionId: 'M-182',
    proposalId: 'P-1020',
    offerId: 'O-392',
    hyungnimName: '한지우',
    kkobungName: '백지훈',
    status: '분쟁중',
    openChatUrl: 'https://open.kakao.com/o/gM182pqr',
    createdAt: '2026-08-16 17:12',
  },
  {
    missionId: 'M-175',
    proposalId: 'P-1008',
    offerId: 'O-380',
    hyungnimName: '백승우',
    kkobungName: '천유빈',
    status: '완료',
    openChatUrl: 'https://open.kakao.com/o/gM175stu',
    createdAt: '2026-08-12 12:38',
  },
]
